#!/bin/bash
# =================================================================
# lang.sh — Локализация (RU / EN)
# =================================================================

VWN_CONF="/usr/local/etc/xray/vwn.conf"
VWN_LANG="${VWN_LANG:-}"

# Загружаем сохранённый язык если не задан
if [ -z "$VWN_LANG" ]; then
    [ -f "$VWN_CONF" ] && source "$VWN_CONF"
    VWN_LANG="${VWN_LANG:-ru}"
fi

selectLang() {
    clear
    echo "┌─────────────────────────────────┐"
    echo "│   Select language / Выберите язык│"
    echo "├─────────────────────────────────┤"
    echo "│   1) 🇷🇺  Русский                │"
    echo "│   2) 🇬🇧  English                │"
    echo "└─────────────────────────────────┘"
    read -rp "Choice / Выбор [1]: " _lang_choice
    case "${_lang_choice:-1}" in
        2) VWN_LANG="en" ;;
        *) VWN_LANG="ru" ;;
    esac
    mkdir -p "$(dirname "$VWN_CONF")"
    # Сохраняем, не трогая остальные настройки
    if [ -f "$VWN_CONF" ]; then
        sed -i '/^VWN_LANG=/d' "$VWN_CONF"
    fi
    echo "VWN_LANG=${VWN_LANG}" >> "$VWN_CONF"
    export VWN_LANG
}

# Инициализация переводов
_initLang() {
    unset MSG
    declare -gA MSG

    # ── ОБЩИЕ ─────────────────────────────────────────────────────
    MSG[yes_no]=$(            [ "$VWN_LANG" = en ] && echo "(y/n)"          || echo "(y/n)")
    MSG[press_enter]=$(       [ "$VWN_LANG" = en ] && echo "Press Enter..."  || echo "Нажмите Enter...")
    MSG[choose]=$(            [ "$VWN_LANG" = en ] && echo "Choose: "        || echo "Выберите: ")
    MSG[back]=$(              [ "$VWN_LANG" = en ] && echo "Back"            || echo "Назад")
    MSG[done]=$(              [ "$VWN_LANG" = en ] && echo "Done."           || echo "Готово.")
    MSG[error]=$(             [ "$VWN_LANG" = en ] && echo "Error"           || echo "Ошибка")
    MSG[invalid]=$(           [ "$VWN_LANG" = en ] && echo "Invalid input!"  || echo "Неверный ввод!")
    MSG[invalid_port]=$(      [ "$VWN_LANG" = en ] && echo "Invalid port."   || echo "Некорректный порт.")
    MSG[run_as_root]=$(       [ "$VWN_LANG" = en ] && echo "Run as root!"    || echo "Запустите от root!")
    MSG[no_logs]=$(           [ "$VWN_LANG" = en ] && echo "No logs"         || echo "Нет логов")
    MSG[cancel]=$(            [ "$VWN_LANG" = en ] && echo "Cancelled."      || echo "Отмена.")
    MSG[restarted]=$(         [ "$VWN_LANG" = en ] && echo "Restarted."      || echo "Перезапущен.")
    MSG[removed]=$(           [ "$VWN_LANG" = en ] && echo "Removed."        || echo "Удалено.")
    MSG[saved]=$(             [ "$VWN_LANG" = en ] && echo "Saved."          || echo "Сохранено.")
    MSG[not_found]=$(         [ "$VWN_LANG" = en ] && echo "Not found."      || echo "Не найдено.")
    MSG[enter_domain]=$(      [ "$VWN_LANG" = en ] && echo "Enter domain: "  || echo "Введите домен: ")
    MSG[current]=$(           [ "$VWN_LANG" = en ] && echo "Current"         || echo "Текущий")
    MSG[status]=$(            [ "$VWN_LANG" = en ] && echo "Status"          || echo "Статус")
    MSG[country]=$(           [ "$VWN_LANG" = en ] && echo "Country"         || echo "Страна")
    MSG[domains_count]=$(     [ "$VWN_LANG" = en ] && echo "Domains"         || echo "Доменов")
    MSG[mode_global]=$(       [ "$VWN_LANG" = en ] && echo "Global"          || echo "Global")
    MSG[mode_split]=$(        [ "$VWN_LANG" = en ] && echo "Split"           || echo "Split")
    MSG[mode_off]=$(          [ "$VWN_LANG" = en ] && echo "route OFF"       || echo "маршрут OFF")
    MSG[unavailable]=$(       [ "$VWN_LANG" = en ] && echo "Unavailable"     || echo "Недоступен")
    MSG[unknown]=$(           [ "$VWN_LANG" = en ] && echo "unknown"         || echo "неизвестно")
    MSG[auto]=$(              [ "$VWN_LANG" = en ] && echo "Auto"            || echo "Авто")
    MSG[enabled]=$(           [ "$VWN_LANG" = en ] && echo "ENABLED"         || echo "ВКЛЮЧЕНО")
    MSG[disabled]=$(          [ "$VWN_LANG" = en ] && echo "DISABLED"        || echo "ВЫКЛЮЧЕНО")
    MSG[all_services_restarted]=$( [ "$VWN_LANG" = en ] && echo "All services restarted." || echo "Все сервисы перезапущены.")

    # ── INSTALL ───────────────────────────────────────────────────
    MSG[install_deps]=$(      [ "$VWN_LANG" = en ] && echo "Installing dependencies..." || echo "Установка зависимостей...")
    MSG[install_modules]=$(   [ "$VWN_LANG" = en ] && echo "Downloading modules..."    || echo "Загрузка модулей...")
    MSG[install_vwn]=$(       [ "$VWN_LANG" = en ] && echo "Installing vwn loader..."  || echo "Установка загрузчика vwn...")
    MSG[install_title]=$(     [ "$VWN_LANG" = en ] && echo "VWN — Xray VLESS + WARP + CDN + Reality installer" || echo "VWN — Установщик Xray VLESS + WARP + CDN + Reality")
    MSG[update_title]=$(      [ "$VWN_LANG" = en ] && echo "VWN — Updating modules"    || echo "VWN — Обновление модулей")
    MSG[update_modules]=$(    [ "$VWN_LANG" = en ] && echo "Updating modules (configs untouched)..." || echo "Обновление модулей (конфиги не затрагиваются)...")
    MSG[update_done]=$(       [ "$VWN_LANG" = en ] && echo "Update complete! Version"  || echo "Обновление завершено! Версия")
    MSG[install_done]=$(      [ "$VWN_LANG" = en ] && echo "Modules installed in"      || echo "Модули установлены в")
    MSG[install_version]=$(   [ "$VWN_LANG" = en ] && echo "Version"                  || echo "Версия")
    MSG[launching_menu]=$(    [ "$VWN_LANG" = en ] && echo "Launching setup menu..."   || echo "Запускаем меню установки...")
    MSG[module_fail]=$(       [ "$VWN_LANG" = en ] && echo "Failed to download"        || echo "Не удалось загрузить")
    MSG[os_unsupported]=$(    [ "$VWN_LANG" = en ] && echo "Only apt/dnf/yum systems supported." || echo "Поддерживаются только apt/dnf/yum системы.")
    MSG[reinstall_hint]=$(    [ "$VWN_LANG" = en ] && echo "Reinstall:"                || echo "Переустановите:")

    # ── MENU ──────────────────────────────────────────────────────
    MSG[menu_title]=$(        [ "$VWN_LANG" = en ] && echo "XRAY VLESS + WARP + CDN + REALITY" || echo "XRAY VLESS + WARP + CDN + REALITY")
    MSG[menu_install]=$(      [ "$VWN_LANG" = en ] && echo "Install Xray (VLESS+WS+TLS+WARP+CDN)"  || echo "Установить Xray (VLESS+WS+TLS+WARP+CDN)")
    MSG[menu_qr]=$(           [ "$VWN_LANG" = en ] && echo "Show QR code and link"     || echo "Показать QR-код и ссылку")
    MSG[menu_uuid]=$(         [ "$VWN_LANG" = en ] && echo "Change UUID"               || echo "Сменить UUID")
    MSG[menu_sep_config]=$(   [ "$VWN_LANG" = en ] && echo "─── Configuration ───────────────────" || echo "─────────────── Конфигурация ─────────────")
    MSG[menu_port]=$(         [ "$VWN_LANG" = en ] && echo "Change Xray port"          || echo "Изменить порт Xray")
    MSG[menu_wspath]=$(       [ "$VWN_LANG" = en ] && echo "Change WebSocket path"     || echo "Изменить путь WebSocket")
    MSG[menu_stub]=$(         [ "$VWN_LANG" = en ] && echo "Change stub site"          || echo "Изменить сайт-заглушку")
    MSG[menu_ssl]=$(          [ "$VWN_LANG" = en ] && echo "Reissue SSL certificate"   || echo "Перевыпустить SSL сертификат")
    MSG[menu_domain]=$(       [ "$VWN_LANG" = en ] && echo "Change domain"             || echo "Сменить домен")
    MSG[menu_sep_cdn]=$(      [ "$VWN_LANG" = en ] && echo "─── CDN & WARP ──────────────────────" || echo "─────────────── CDN и WARP ───────────────")
    MSG[menu_cdn]=$(          [ "$VWN_LANG" = en ] && echo "Toggle CDN mode (ON/OFF)"  || echo "Переключить CDN режим (ON/OFF)")
    MSG[menu_warp_mode]=$(    [ "$VWN_LANG" = en ] && echo "Toggle WARP mode (Global/Split/OFF)" || echo "Переключить режим WARP (Global/Split/OFF)")
    MSG[menu_warp_add]=$(     [ "$VWN_LANG" = en ] && echo "Add domain to WARP"        || echo "Добавить домен в WARP")
    MSG[menu_warp_del]=$(     [ "$VWN_LANG" = en ] && echo "Remove domain from WARP"   || echo "Удалить домен из WARP")
    MSG[menu_warp_edit]=$(    [ "$VWN_LANG" = en ] && echo "Edit WARP list (Nano)"     || echo "Редактировать список WARP (Nano)")
    MSG[menu_warp_check]=$(   [ "$VWN_LANG" = en ] && echo "Check IP (Real vs WARP)"   || echo "Проверить IP (Real vs WARP)")
    MSG[menu_sep_sec]=$(      [ "$VWN_LANG" = en ] && echo "─── Security ────────────────────────" || echo "─────────────── Безопасность ─────────────")
    MSG[menu_bbr]=$(          [ "$VWN_LANG" = en ] && echo "Enable BBR"                || echo "Включить BBR")
    MSG[menu_f2b]=$(          [ "$VWN_LANG" = en ] && echo "Enable Fail2Ban"           || echo "Включить Fail2Ban")
    MSG[menu_jail]=$(         [ "$VWN_LANG" = en ] && echo "Enable Web-Jail"           || echo "Включить Web-Jail")
    MSG[menu_ssh]=$(          [ "$VWN_LANG" = en ] && echo "Change SSH port"           || echo "Сменить SSH порт")
    MSG[menu_watchdog]=$(     [ "$VWN_LANG" = en ] && echo "Install WARP Watchdog"     || echo "Установить WARP Watchdog")
    MSG[menu_sep_logs]=$(     [ "$VWN_LANG" = en ] && echo "─── Logs ────────────────────────────" || echo "─────────────── Логи ─────────────────────")
    MSG[menu_xray_acc]=$(     [ "$VWN_LANG" = en ] && echo "Xray logs (access)"        || echo "Логи Xray (access)")
    MSG[menu_xray_err]=$(     [ "$VWN_LANG" = en ] && echo "Xray logs (error)"         || echo "Логи Xray (error)")
    MSG[menu_nginx_acc]=$(    [ "$VWN_LANG" = en ] && echo "Nginx logs (access)"       || echo "Логи Nginx (access)")
    MSG[menu_nginx_err]=$(    [ "$VWN_LANG" = en ] && echo "Nginx logs (error)"        || echo "Логи Nginx (error)")
    MSG[menu_clear_logs]=$(   [ "$VWN_LANG" = en ] && echo "Clear all logs"            || echo "Очистить все логи")
    MSG[menu_sep_svc]=$(      [ "$VWN_LANG" = en ] && echo "─── Services ────────────────────────" || echo "─────────────── Сервисы ──────────────────")
    MSG[menu_restart]=$(      [ "$VWN_LANG" = en ] && echo "Restart all services"      || echo "Перезапустить все сервисы")
    MSG[menu_update_xray]=$(  [ "$VWN_LANG" = en ] && echo "Update Xray-core"          || echo "Обновить Xray-core")
    MSG[menu_remove]=$(       [ "$VWN_LANG" = en ] && echo "Full removal"              || echo "Полное удаление")
    MSG[menu_sep_ufw]=$(      [ "$VWN_LANG" = en ] && echo "─── UFW, SSL, Logs ──────────────────" || echo "─────────────── UFW, SSL, Logs ───────────")
    MSG[menu_ufw]=$(          [ "$VWN_LANG" = en ] && echo "Manage UFW"                || echo "Управление UFW")
    MSG[menu_ssl_cron]=$(     [ "$VWN_LANG" = en ] && echo "Manage SSL auto-renewal"   || echo "Управление автообновлением SSL")
    MSG[menu_log_cron]=$(     [ "$VWN_LANG" = en ] && echo "Manage log auto-clear"     || echo "Управление автоочисткой логов")
    MSG[menu_sep_tun]=$(      [ "$VWN_LANG" = en ] && echo "─── Tunnels ─────────────────────────" || echo "─────────────── Туннели ──────────────────")
    MSG[menu_reality]=$(      [ "$VWN_LANG" = en ] && echo "Manage VLESS + Reality"    || echo "Управление VLESS + Reality")
    MSG[menu_relay]=$(        [ "$VWN_LANG" = en ] && echo "Manage Relay (external)"   || echo "Управление Relay (внешний сервер)")
    MSG[menu_psiphon]=$(      [ "$VWN_LANG" = en ] && echo "Manage Psiphon"            || echo "Управление Psiphon")
    MSG[menu_tor]=$(          [ "$VWN_LANG" = en ] && echo "Manage Tor"                || echo "Управление Tor")
    MSG[menu_lang]=$(         [ "$VWN_LANG" = en ] && echo "Change language / Сменить язык" || echo "Сменить язык / Change language")
    MSG[menu_sep_exit]=$(     [ "$VWN_LANG" = en ] && echo "─── Exit ────────────────────────────" || echo "─────────────── Выход ────────────────────")
    MSG[menu_exit]=$(         [ "$VWN_LANG" = en ] && echo "Exit"                      || echo "Выйти")

    # ── XRAY / INSTALL ────────────────────────────────────────────
    MSG[install_xray_title]=$( [ "$VWN_LANG" = en ] && echo ">>> Installing Xray VLESS + WARP + CDN + Reality <<<" || echo ">>> Установка Xray VLESS + WARP + CDN + Reality <<<")
    MSG[enter_domain_vpn]=$(  [ "$VWN_LANG" = en ] && echo "Enter domain (vpn.example.com): " || echo "Введите Домен (vpn.example.com): ")
    MSG[domain_required]=$(   [ "$VWN_LANG" = en ] && echo "Domain is required!"       || echo "Домен обязателен!")
    MSG[enter_xray_port]=$(   [ "$VWN_LANG" = en ] && echo "Xray port [16500]: "       || echo "Порт Xray [16500]: ")
    MSG[enter_stub_url]=$(    [ "$VWN_LANG" = en ] && echo "Stub site [https://httpbin.org/]: " || echo "Сайт-заглушка [https://httpbin.org/]: ")
    MSG[install_complete]=$(  [ "$VWN_LANG" = en ] && echo "Installation complete!"    || echo "Установка завершена!")
    MSG[new_uuid]=$(          [ "$VWN_LANG" = en ] && echo "New UUID"                  || echo "Новый UUID")
    MSG[new_path]=$(          [ "$VWN_LANG" = en ] && echo "New Path"                  || echo "Новый путь")
    MSG[port_changed]=$(      [ "$VWN_LANG" = en ] && echo "Port changed to"           || echo "Порт изменён на")
    MSG[proxy_updated]=$(     [ "$VWN_LANG" = en ] && echo "Proxy Pass updated."       || echo "Proxy Pass обновлён.")
    MSG[enter_new_port]=$(    [ "$VWN_LANG" = en ] && echo "New Xray port"             || echo "Новый порт Xray")
    MSG[enter_new_path]=$(    [ "$VWN_LANG" = en ] && echo "New path (Enter = random): " || echo "Новый путь (Enter = случайный): ")
    MSG[enter_proxy_url]=$(   [ "$VWN_LANG" = en ] && echo "New Proxy Pass URL (e.g. https://google.com): " || echo "Новый Proxy Pass URL (например https://google.com): ")
    MSG[enter_new_domain]=$(  [ "$VWN_LANG" = en ] && echo "Enter new domain: "        || echo "Введите новый домен: ")
    MSG[current_domain]=$(    [ "$VWN_LANG" = en ] && echo "Current domain"            || echo "Текущий домен")
    MSG[xray_updated]=$(      [ "$VWN_LANG" = en ] && echo "Xray-core updated."        || echo "Xray-core обновлён.")
    MSG[xray_not_installed]=$( [ "$VWN_LANG" = en ] && echo "Xray not installed."      || echo "Xray не установлен.")

    # ── REMOVAL ───────────────────────────────────────────────────
    MSG[remove_confirm]=$(    [ "$VWN_LANG" = en ] && echo "Remove Xray, Nginx, WARP, Psiphon and all configs?" || echo "Удалить Xray, Nginx, WARP, Psiphon и все конфиги?")
    MSG[remove_done]=$(       [ "$VWN_LANG" = en ] && echo "Removal complete."         || echo "Удаление завершено.")

    # ── NGINX / SSL ───────────────────────────────────────────────
    MSG[nginx_syntax_err]=$(  [ "$VWN_LANG" = en ] && echo "Nginx syntax error!"       || echo "Ошибка синтаксиса nginx!")
    MSG[cf_ips_setup]=$(      [ "$VWN_LANG" = en ] && echo "Setting up Cloudflare IPs..." || echo "Настройка Cloudflare IP...")
    MSG[cf_ips_ok]=$(         [ "$VWN_LANG" = en ] && echo "Cloudflare IPs configured." || echo "Cloudflare IPs настроены.")
    MSG[cf_ips_fail]=$(       [ "$VWN_LANG" = en ] && echo "Error: no Cloudflare IPs received." || echo "Ошибка: не получен ни один IP Cloudflare.")
    MSG[cdn_disable_confirm]=$( [ "$VWN_LANG" = en ] && echo "CDN mode active. Disable?" || echo "CDN режим активен. Отключить?")
    MSG[cdn_disabled]=$(      [ "$VWN_LANG" = en ] && echo "CDN mode disabled."        || echo "CDN режим отключен.")
    MSG[cdn_enabled]=$(       [ "$VWN_LANG" = en ] && echo "CDN mode enabled."         || echo "CDN режим включён.")
    MSG[cdn_enabling]=$(      [ "$VWN_LANG" = en ] && echo "Enabling CDN mode..."      || echo "Включение CDN режима...")
    MSG[ssl_method]=$(        [ "$VWN_LANG" = en ] && echo "SSL method:"               || echo "Метод SSL:")
    MSG[ssl_method_1]=$(      [ "$VWN_LANG" = en ] && echo "1) Cloudflare DNS API (port 80 not needed)" || echo "1) Cloudflare DNS API (порт 80 не нужен)")
    MSG[ssl_method_2]=$(      [ "$VWN_LANG" = en ] && echo "2) Standalone (temporarily open port 80)" || echo "2) Standalone (временно открыть порт 80)")
    MSG[ssl_your_choice]=$(   [ "$VWN_LANG" = en ] && echo "Your choice: "             || echo "Ваш выбор: ")
    MSG[ssl_enter_domain]=$(  [ "$VWN_LANG" = en ] && echo "Enter domain for SSL: "    || echo "Введите домен для выпуска SSL: ")
    MSG[ssl_domain_empty]=$(  [ "$VWN_LANG" = en ] && echo "Domain not set."           || echo "Домен не задан.")
    MSG[ssl_cf_email]=$(      [ "$VWN_LANG" = en ] && echo "Cloudflare Email: "        || echo "Cloudflare Email: ")
    MSG[ssl_cf_key]=$(        [ "$VWN_LANG" = en ] && echo "Cloudflare Global API Key: " || echo "Cloudflare Global API Key: ")
    MSG[ssl_success]=$(       [ "$VWN_LANG" = en ] && echo "SSL configured for"        || echo "SSL успешно настроен для")

    # ── WARP ──────────────────────────────────────────────────────
    MSG[warp_connected]=$(    [ "$VWN_LANG" = en ] && echo "WARP connected successfully!" || echo "WARP успешно подключен!")
    MSG[warp_started]=$(      [ "$VWN_LANG" = en ] && echo "WARP started but check failed. Continuing..." || echo "WARP запущен, но проверка не прошла. Продолжаем...")
    MSG[warp_mode_choose]=$(  [ "$VWN_LANG" = en ] && echo "Select WARP mode:"         || echo "Выберите режим работы WARP:")
    MSG[warp_mode_1]=$(       [ "$VWN_LANG" = en ] && echo "1) Global — all traffic through WARP" || echo "1) Global — весь трафик через WARP")
    MSG[warp_mode_2]=$(       [ "$VWN_LANG" = en ] && echo "2) Split — only domain list" || echo "2) Split — только список доменов")
    MSG[warp_mode_3]=$(       [ "$VWN_LANG" = en ] && echo "3) OFF — disable WARP from Xray" || echo "3) OFF — отключить WARP от Xray")
    MSG[warp_mode_0]=$(       [ "$VWN_LANG" = en ] && echo "0) Back"                   || echo "0) Назад")
    MSG[warp_global_ok]=$(    [ "$VWN_LANG" = en ] && echo "Global: All traffic through WARP." || echo "Global: Весь трафик через WARP.")
    MSG[warp_split_ok]=$(     [ "$VWN_LANG" = en ] && echo "Split: Only domain list through WARP." || echo "Split: Только список доменов через WARP.")
    MSG[warp_off_ok]=$(       [ "$VWN_LANG" = en ] && echo "WARP disabled from Xray."  || echo "WARP отключён от Xray.")
    MSG[warp_domain_add]=$(   [ "$VWN_LANG" = en ] && echo "Domain for WARP (e.g. netflix.com): " || echo "Домен для WARP (например, netflix.com): ")
    MSG[warp_domain_added]=$( [ "$VWN_LANG" = en ] && echo "Domain added."             || echo "Домен добавлен.")
    MSG[warp_domain_exists]=$( [ "$VWN_LANG" = en ] && echo "Domain already in list."  || echo "Домен уже в списке.")
    MSG[warp_domain_del]=$(   [ "$VWN_LANG" = en ] && echo "Enter number to delete: "  || echo "Введите номер для удаления: ")
    MSG[warp_domain_removed]=$( [ "$VWN_LANG" = en ] && echo "Domain removed."         || echo "Домен удален.")
    MSG[warp_list_empty]=$(   [ "$VWN_LANG" = en ] && echo "List is empty."            || echo "Список пуст.")
    MSG[warp_watchdog_ok]=$(  [ "$VWN_LANG" = en ] && echo "WARP watchdog installed."  || echo "WARP watchdog установлен.")
    MSG[warp_real_ip]=$(      [ "$VWN_LANG" = en ] && echo "Server real IP"            || echo "Реальный IP сервера")
    MSG[warp_ip]=$(           [ "$VWN_LANG" = en ] && echo "IP via WARP SOCKS"         || echo "IP через WARP SOCKS")

    # ── SECURITY ──────────────────────────────────────────────────
    MSG[ssh_new_port]=$(      [ "$VWN_LANG" = en ] && echo "Enter new SSH port [22]: " || echo "Введите новый SSH порт [22]: ")
    MSG[ssh_changed]=$(       [ "$VWN_LANG" = en ] && echo "SSH port changed to"       || echo "SSH порт изменен на")
    MSG[ssh_close_old]=$(     [ "$VWN_LANG" = en ] && echo "Close old port: ufw delete allow 22/tcp" || echo "Закройте старый порт: ufw delete allow 22/tcp")
    MSG[bbr_active]=$(        [ "$VWN_LANG" = en ] && echo "BBR already active."       || echo "BBR уже активен.")
    MSG[bbr_enabled]=$(       [ "$VWN_LANG" = en ] && echo "BBR enabled."              || echo "BBR включен.")
    MSG[f2b_setup]=$(         [ "$VWN_LANG" = en ] && echo "Configuring Fail2Ban..."   || echo "Настройка Fail2Ban...")
    MSG[f2b_ok]=$(            [ "$VWN_LANG" = en ] && echo "Fail2Ban configured (SSH on port" || echo "Fail2Ban настроен (SSH на порту")
    MSG[webjail_setup]=$(     [ "$VWN_LANG" = en ] && echo "Configuring Web-Jail..."   || echo "Настройка Web-Jail...")
    MSG[webjail_ok]=$(        [ "$VWN_LANG" = en ] && echo "Web-Jail activated."       || echo "Web-Jail активирован.")
    MSG[sysctl_ok]=$(         [ "$VWN_LANG" = en ] && echo "System parameters applied (Anti-Ping, IPv6 disabled)." || echo "Системные параметры применены (Anti-Ping, IPv6 отключён).")
    MSG[ufw_title]=$(         [ "$VWN_LANG" = en ] && echo "=== UFW Firewall Management ===" || echo "=== Управление UFW Firewall ===")
    MSG[ufw_inactive]=$(      [ "$VWN_LANG" = en ] && echo "UFW inactive"              || echo "UFW не активен")
    MSG[ufw_open_port]=$(     [ "$VWN_LANG" = en ] && echo "Open port"                 || echo "Открыть порт")
    MSG[ufw_close_port]=$(    [ "$VWN_LANG" = en ] && echo "Close port"                || echo "Закрыть порт")
    MSG[ufw_enable]=$(        [ "$VWN_LANG" = en ] && echo "Enable UFW"                || echo "Включить UFW")
    MSG[ufw_disable]=$(       [ "$VWN_LANG" = en ] && echo "Disable UFW"               || echo "Выключить UFW")
    MSG[ufw_reset]=$(         [ "$VWN_LANG" = en ] && echo "Reset UFW"                 || echo "Сбросить UFW")
    MSG[ufw_reset_confirm]=$( [ "$VWN_LANG" = en ] && echo "Delete ALL rules?"         || echo "Удалить ВСЕ правила?")
    MSG[ufw_port_prompt]=$(   [ "$VWN_LANG" = en ] && echo "Port: "                    || echo "Порт: ")
    MSG[ufw_proto_prompt]=$(  [ "$VWN_LANG" = en ] && echo "Protocol [tcp/udp/any]: "  || echo "Протокол [tcp/udp/any]: ")
    MSG[ufw_port_opened]=$(   [ "$VWN_LANG" = en ] && echo "Port opened"               || echo "Порт открыт")
    MSG[ufw_port_closed]=$(   [ "$VWN_LANG" = en ] && echo "Port closed"               || echo "Порт закрыт")
    MSG[ufw_close_prompt]=$(  [ "$VWN_LANG" = en ] && echo "Port to close: "           || echo "Порт для закрытия: ")
    MSG[ufw_enabled]=$(       [ "$VWN_LANG" = en ] && echo "UFW enabled"               || echo "UFW включен")
    MSG[ufw_disabled]=$(      [ "$VWN_LANG" = en ] && echo "UFW disabled"              || echo "UFW выключен")
    MSG[ufw_reset_ok]=$(      [ "$VWN_LANG" = en ] && echo "UFW reset"                 || echo "UFW сброшен")

    # ── LOGS ──────────────────────────────────────────────────────
    MSG[logs_clearing]=$(     [ "$VWN_LANG" = en ] && echo "Clearing logs..."          || echo "Очистка логов...")
    MSG[logs_cleared]=$(      [ "$VWN_LANG" = en ] && echo "Logs cleared."             || echo "Логи очищены.")
    MSG[logrotate_ok]=$(      [ "$VWN_LANG" = en ] && echo "Log rotation configured."  || echo "Авто-ротация логов настроена.")
    MSG[ssl_cron_enabled]=$(  [ "$VWN_LANG" = en ] && echo "SSL auto-renewal enabled." || echo "Автообновление SSL включено.")
    MSG[ssl_cron_disabled]=$( [ "$VWN_LANG" = en ] && echo "SSL auto-renewal disabled." || echo "Автообновление SSL отключено.")
    MSG[log_cron_enabled]=$(  [ "$VWN_LANG" = en ] && echo "Log auto-clear enabled (Sun 04:00)." || echo "Автоочистка логов настроена (воскр. 04:00).")
    MSG[log_cron_disabled]=$( [ "$VWN_LANG" = en ] && echo "Log auto-clear disabled."  || echo "Автоочистка логов отключена.")
    MSG[ssl_cron_title]=$(    [ "$VWN_LANG" = en ] && echo "=== SSL Auto-Renewal Management ===" || echo "=== Управление автообновлением SSL ===")
    MSG[log_cron_title]=$(    [ "$VWN_LANG" = en ] && echo "=== Log Auto-Clear Management ===" || echo "=== Управление автоочисткой логов ===")
    MSG[cron_enable]=$(       [ "$VWN_LANG" = en ] && echo "Enable"                    || echo "Включить")
    MSG[cron_disable]=$(      [ "$VWN_LANG" = en ] && echo "Disable"                   || echo "Выключить")
    MSG[cron_show]=$(         [ "$VWN_LANG" = en ] && echo "Show task"                 || echo "Показать задачу")
    MSG[cron_no_task]=$(      [ "$VWN_LANG" = en ] && echo "No task."                  || echo "Нет задачи.")

    # ── REALITY ───────────────────────────────────────────────────
    MSG[reality_title]=$(     [ "$VWN_LANG" = en ] && echo "=== VLESS + Reality Management ===" || echo "=== Управление VLESS + Reality ===")
    MSG[reality_install]=$(   [ "$VWN_LANG" = en ] && echo "Install Reality"           || echo "Установить Reality")
    MSG[reality_qr]=$(        [ "$VWN_LANG" = en ] && echo "Show QR code and link"     || echo "Показать QR-код и ссылку")
    MSG[reality_info]=$(      [ "$VWN_LANG" = en ] && echo "Show client parameters"    || echo "Показать параметры клиента")
    MSG[reality_uuid]=$(      [ "$VWN_LANG" = en ] && echo "Change UUID"               || echo "Сменить UUID")
    MSG[reality_port]=$(      [ "$VWN_LANG" = en ] && echo "Change port"               || echo "Изменить порт")
    MSG[reality_dest]=$(      [ "$VWN_LANG" = en ] && echo "Change dest (mask site)"   || echo "Изменить dest (сайт маскировки)")
    MSG[reality_restart]=$(   [ "$VWN_LANG" = en ] && echo "Restart service"           || echo "Перезапустить сервис")
    MSG[reality_logs]=$(      [ "$VWN_LANG" = en ] && echo "Reality logs"              || echo "Логи Reality")
    MSG[reality_remove]=$(    [ "$VWN_LANG" = en ] && echo "Remove Reality"            || echo "Удалить Reality")
    MSG[reality_setup_title]=$( [ "$VWN_LANG" = en ] && echo "=== Installing VLESS + Reality ===" || echo "=== Установка VLESS + Reality ===")
    MSG[reality_port_prompt]=$( [ "$VWN_LANG" = en ] && echo "Reality port [8443]: "   || echo "Порт Reality [8443]: ")
    MSG[reality_dest_title]=$( [ "$VWN_LANG" = en ] && echo "Masquerade site (dest):" || echo "Сайт для маскировки (dest):")
    MSG[reality_dest_custom]=$( [ "$VWN_LANG" = en ] && echo "4) Enter custom"         || echo "4) Ввести свой")
    MSG[reality_dest_prompt]=$( [ "$VWN_LANG" = en ] && echo "Enter dest (host:port): " || echo "Введите dest (host:port): ")
    MSG[reality_dest_empty]=$(  [ "$VWN_LANG" = en ] && echo "Dest not specified."     || echo "Dest не указан.")
    MSG[reality_keygen]=$(    [ "$VWN_LANG" = en ] && echo "Generating Reality keys..." || echo "Генерация ключей Reality...")
    MSG[reality_keys_fail]=$( [ "$VWN_LANG" = en ] && echo "Error: xray x25519 not working" || echo "Ошибка: xray x25519 не работает")
    MSG[reality_keys_err]=$(  [ "$VWN_LANG" = en ] && echo "Error getting keys"        || echo "Ошибка получения ключей")
    MSG[reality_config_ok]=$( [ "$VWN_LANG" = en ] && echo "Reality config created."   || echo "Reality конфиг создан.")
    MSG[reality_service_ok]=$( [ "$VWN_LANG" = en ] && echo "xray-reality service started." || echo "xray-reality сервис запущен.")
    MSG[reality_installed]=$( [ "$VWN_LANG" = en ] && echo "Reality installed!"        || echo "Reality установлен!")
    MSG[reality_hint_domains]=$( [ "$VWN_LANG" = en ] && echo "Add domains to list (item 3) for Split mode." || echo "Добавьте домены в список (пункт 3) для Split режима.")
    MSG[reality_not_installed]=$( [ "$VWN_LANG" = en ] && echo "Reality not installed." || echo "Reality не установлен.")
    MSG[reality_port_changed]=$( [ "$VWN_LANG" = en ] && echo "Reality port changed to" || echo "Порт Reality изменён на")
    MSG[reality_dest_changed]=$( [ "$VWN_LANG" = en ] && echo "Dest changed to"        || echo "Dest изменён на")
    MSG[reality_remove_confirm]=$( [ "$VWN_LANG" = en ] && echo "Remove Reality?"      || echo "Удалить Reality?")
    MSG[reality_current_dest]=$( [ "$VWN_LANG" = en ] && echo "Current dest"           || echo "Текущий dest")
    MSG[reality_open_port]=$( [ "$VWN_LANG" = en ] && echo "Opening port"             || echo "Открываем порт")
    MSG[reality_ufw]=$(       [ "$VWN_LANG" = en ] && echo "in UFW..."                 || echo "в UFW...")

    # ── RELAY ─────────────────────────────────────────────────────
    MSG[relay_title]=$(       [ "$VWN_LANG" = en ] && echo "=== Relay Management ===" || echo "=== Управление Relay ===")
    MSG[relay_setup]=$(       [ "$VWN_LANG" = en ] && echo "Configure relay (paste link)" || echo "Настроить реле (вставить ссылку)")
    MSG[relay_mode]=$(        [ "$VWN_LANG" = en ] && echo "Toggle mode (Global/Split/OFF)" || echo "Переключить режим (Global/Split/OFF)")
    MSG[relay_add]=$(         [ "$VWN_LANG" = en ] && echo "Add domain to list"        || echo "Добавить домен в список")
    MSG[relay_del]=$(         [ "$VWN_LANG" = en ] && echo "Remove domain from list"   || echo "Удалить домен из списка")
    MSG[relay_edit]=$(        [ "$VWN_LANG" = en ] && echo "Edit domain list (Nano)"   || echo "Редактировать список доменов (Nano)")
    MSG[relay_check]=$(       [ "$VWN_LANG" = en ] && echo "Check IP via relay"        || echo "Проверить IP через реле")
    MSG[relay_remove]=$(      [ "$VWN_LANG" = en ] && echo "Remove relay"              || echo "Удалить реле")
    MSG[relay_server]=$(      [ "$VWN_LANG" = en ] && echo "Server"                    || echo "Сервер")
    MSG[relay_paste_url]=$(   [ "$VWN_LANG" = en ] && echo "Paste link (vless:// vmess:// trojan:// socks5://):" || echo "Вставьте ссылку (vless:// vmess:// trojan:// socks5://):")
    MSG[relay_unknown_proto]=$( [ "$VWN_LANG" = en ] && echo "Unknown protocol"        || echo "Неизвестный протокол")
    MSG[relay_parse_fail]=$(  [ "$VWN_LANG" = en ] && echo "Could not parse address/port." || echo "Не удалось распарсить адрес/порт.")
    MSG[relay_configured]=$(  [ "$VWN_LANG" = en ] && echo "Relay configured"          || echo "Реле настроено")
    MSG[relay_not_configured]=$( [ "$VWN_LANG" = en ] && echo "Relay not configured."  || echo "Реле не настроено.")
    MSG[relay_mode_1]=$(      [ "$VWN_LANG" = en ] && echo "1) Global — all traffic through relay" || echo "1) Global — весь трафик через реле")
    MSG[relay_mode_2]=$(      [ "$VWN_LANG" = en ] && echo "2) Split — only domain list" || echo "2) Split — только список доменов")
    MSG[relay_mode_3]=$(      [ "$VWN_LANG" = en ] && echo "3) OFF — disable relay from Xray" || echo "3) OFF — отключить реле от Xray")
    MSG[relay_global_ok]=$(   [ "$VWN_LANG" = en ] && echo "Relay Global: all traffic through relay." || echo "Relay Global: весь трафик через реле.")
    MSG[relay_split_ok]=$(    [ "$VWN_LANG" = en ] && echo "Relay Split applied."      || echo "Relay Split применён.")
    MSG[relay_off_ok]=$(      [ "$VWN_LANG" = en ] && echo "Relay disabled from Xray." || echo "Реле отключено от Xray.")
    MSG[relay_domain_prompt]=$( [ "$VWN_LANG" = en ] && echo "Domain (e.g. netflix.com): " || echo "Домен (например netflix.com): ")
    MSG[relay_domain_added]=$( [ "$VWN_LANG" = en ] && echo "Domain added."            || echo "Домен добавлен.")
    MSG[relay_remove_confirm]=$( [ "$VWN_LANG" = en ] && echo "Remove relay?"          || echo "Удалить реле?")
    MSG[relay_removed]=$(     [ "$VWN_LANG" = en ] && echo "Relay removed."            || echo "Реле удалено.")
    MSG[relay_setup_first]=$( [ "$VWN_LANG" = en ] && echo "Configure relay first (item 1)" || echo "Сначала настройте реле (п.1)")
    MSG[relay_real_ip]=$(     [ "$VWN_LANG" = en ] && echo "Server real IP"            || echo "Реальный IP сервера")
    MSG[relay_ip]=$(          [ "$VWN_LANG" = en ] && echo "IP via relay"              || echo "IP через реле")
    MSG[relay_checking]=$(    [ "$VWN_LANG" = en ] && echo "Checking via relay..."     || echo "Проверка через реле...")

    # ── PSIPHON ───────────────────────────────────────────────────
    MSG[psiphon_title]=$(     [ "$VWN_LANG" = en ] && echo "=== Psiphon Management ===" || echo "=== Управление Psiphon ===")
    MSG[psiphon_install]=$(   [ "$VWN_LANG" = en ] && echo "Install Psiphon"           || echo "Установить Psiphon")
    MSG[psiphon_mode]=$(      [ "$VWN_LANG" = en ] && echo "Toggle mode (Global/Split/OFF)" || echo "Переключить режим (Global/Split/OFF)")
    MSG[psiphon_add]=$(       [ "$VWN_LANG" = en ] && echo "Add domain to list"        || echo "Добавить домен в список")
    MSG[psiphon_del]=$(       [ "$VWN_LANG" = en ] && echo "Remove domain from list"   || echo "Удалить домен из списка")
    MSG[psiphon_edit]=$(      [ "$VWN_LANG" = en ] && echo "Edit domain list (Nano)"   || echo "Редактировать список доменов (Nano)")
    MSG[psiphon_country]=$(   [ "$VWN_LANG" = en ] && echo "Change exit country"       || echo "Сменить страну выхода")
    MSG[psiphon_check]=$(     [ "$VWN_LANG" = en ] && echo "Check IP via Psiphon"      || echo "Проверить IP через Psiphon")
    MSG[psiphon_restart]=$(   [ "$VWN_LANG" = en ] && echo "Restart"                   || echo "Перезапустить")
    MSG[psiphon_logs]=$(      [ "$VWN_LANG" = en ] && echo "Psiphon logs"              || echo "Логи Psiphon")
    MSG[psiphon_remove]=$(    [ "$VWN_LANG" = en ] && echo "Remove Psiphon"            || echo "Удалить Psiphon")
    MSG[psiphon_socks5]=$(    [ "$VWN_LANG" = en ] && echo "SOCKS5"                    || echo "SOCKS5")
    MSG[psiphon_setup_title]=$( [ "$VWN_LANG" = en ] && echo "=== Installing Psiphon ===" || echo "=== Установка Psiphon ===")
    MSG[psiphon_dl]=$(        [ "$VWN_LANG" = en ] && echo "Downloading Psiphon tunnel core..." || echo "Скачивание Psiphon tunnel core...")
    MSG[psiphon_arch_unsupported]=$( [ "$VWN_LANG" = en ] && echo "Architecture not supported." || echo "Архитектура не поддерживается.")
    MSG[psiphon_dl_fail]=$(   [ "$VWN_LANG" = en ] && echo "Error downloading Psiphon." || echo "Ошибка скачивания Psiphon.")
    MSG[psiphon_installed_bin]=$( [ "$VWN_LANG" = en ] && echo "Psiphon installed"     || echo "Psiphon установлен")
    MSG[psiphon_already]=$(   [ "$VWN_LANG" = en ] && echo "psiphon already installed." || echo "psiphon уже установлен.")
    MSG[psiphon_country_select]=$( [ "$VWN_LANG" = en ] && echo "Select exit country:" || echo "Выберите страну выхода:")
    MSG[psiphon_country_auto]=$( [ "$VWN_LANG" = en ] && echo "9) Auto (any country)"  || echo "9) Авто (любая страна)")
    MSG[psiphon_country_manual]=$( [ "$VWN_LANG" = en ] && echo "10) Enter code manually" || echo "10) Ввести код вручную")
    MSG[psiphon_country_prompt]=$( [ "$VWN_LANG" = en ] && echo "Country code (AT AU BE BG CA CH CZ DE DK EE ES FI FR GB HR HU IE IN IT JP LV NL NO PL PT RO RS SE SG SK US): " || echo "Код страны (AT AU BE BG CA CH CZ DE DK EE ES FI FR GB HR HU IE IN IT JP LV NL NO PL PT RO RS SE SG SK US): ")
    MSG[psiphon_running]=$(   [ "$VWN_LANG" = en ] && echo "Psiphon started and working." || echo "Psiphon запущен и работает.")
    MSG[psiphon_started]=$(   [ "$VWN_LANG" = en ] && echo "Psiphon started but check failed. May need time to connect." || echo "Psiphon запущен, но проверка не прошла. Может потребоваться время для подключения.")
    MSG[psiphon_installed]=$( [ "$VWN_LANG" = en ] && echo "Psiphon installed!"        || echo "Psiphon установлен!")
    MSG[psiphon_hint]=$(      [ "$VWN_LANG" = en ] && echo "Add domains (item 3) for Split mode." || echo "Добавьте домены в список (пункт 3) для Split режима.")
    MSG[psiphon_not_installed]=$( [ "$VWN_LANG" = en ] && echo "Install Psiphon first (item 1)" || echo "Сначала установите Psiphon (п.1)")
    MSG[psiphon_not_setup]=$( [ "$VWN_LANG" = en ] && echo "Psiphon not configured."   || echo "Psiphon не настроен.")
    MSG[psiphon_mode_1]=$(    [ "$VWN_LANG" = en ] && echo "1) Global — all traffic through Psiphon" || echo "1) Global — весь трафик через Psiphon")
    MSG[psiphon_mode_2]=$(    [ "$VWN_LANG" = en ] && echo "2) Split — only domain list" || echo "2) Split — только список доменов")
    MSG[psiphon_mode_3]=$(    [ "$VWN_LANG" = en ] && echo "3) OFF — disable Psiphon from Xray" || echo "3) OFF — отключить Psiphon от Xray")
    MSG[psiphon_global_ok]=$( [ "$VWN_LANG" = en ] && echo "Psiphon Global: all traffic through Psiphon." || echo "Psiphon Global: весь трафик через Psiphon.")
    MSG[psiphon_split_ok]=$(  [ "$VWN_LANG" = en ] && echo "Psiphon Split applied."    || echo "Psiphon Split применён.")
    MSG[psiphon_off_ok]=$(    [ "$VWN_LANG" = en ] && echo "Psiphon disabled from Xray." || echo "Psiphon отключён от Xray.")
    MSG[psiphon_domain_prompt]=$( [ "$VWN_LANG" = en ] && echo "Domain (e.g. rutracker.org): " || echo "Домен (например rutracker.org): ")
    MSG[psiphon_domain_added]=$( [ "$VWN_LANG" = en ] && echo "Domain added."          || echo "Домен добавлен.")
    MSG[psiphon_country_changed]=$( [ "$VWN_LANG" = en ] && echo "Country changed to"  || echo "Страна изменена на")
    MSG[psiphon_country_restarting]=$( [ "$VWN_LANG" = en ] && echo "Restarting..."    || echo "Перезапуск...")
    MSG[psiphon_remove_confirm]=$( [ "$VWN_LANG" = en ] && echo "Remove Psiphon?"      || echo "Удалить Psiphon?")
    MSG[psiphon_real_ip]=$(   [ "$VWN_LANG" = en ] && echo "Server real IP"            || echo "Реальный IP сервера")
    MSG[psiphon_ip]=$(        [ "$VWN_LANG" = en ] && echo "IP via Psiphon"            || echo "IP через Psiphon")
    MSG[psiphon_exit_country]=$( [ "$VWN_LANG" = en ] && echo "Exit country"           || echo "Страна выхода")
    MSG[psiphon_change_country]=$( [ "$VWN_LANG" = en ] && echo "Change Psiphon country:" || echo "Смена страны Psiphon:")

    # ── TOR ───────────────────────────────────────────────────────
    MSG[tor_title]=$(         [ "$VWN_LANG" = en ] && echo "=== Tor Management ===" || echo "=== Управление Tor ===")
    MSG[tor_install]=$(       [ "$VWN_LANG" = en ] && echo "Install Tor"               || echo "Установить Tor")
    MSG[tor_mode]=$(          [ "$VWN_LANG" = en ] && echo "Toggle mode (Global/Split/OFF)" || echo "Переключить режим (Global/Split/OFF)")
    MSG[tor_add]=$(           [ "$VWN_LANG" = en ] && echo "Add domain to list"        || echo "Добавить домен в список")
    MSG[tor_del]=$(           [ "$VWN_LANG" = en ] && echo "Remove domain from list"   || echo "Удалить домен из списка")
    MSG[tor_edit]=$(          [ "$VWN_LANG" = en ] && echo "Edit domain list (Nano)"   || echo "Редактировать список доменов (Nano)")
    MSG[tor_country]=$(       [ "$VWN_LANG" = en ] && echo "Change exit country"       || echo "Сменить страну выхода")
    MSG[tor_check]=$(         [ "$VWN_LANG" = en ] && echo "Check IP via Tor"          || echo "Проверить IP через Tor")
    MSG[tor_renew]=$(         [ "$VWN_LANG" = en ] && echo "Renew circuit (new IP)"    || echo "Обновить цепь (новый IP)")
    MSG[tor_restart]=$(       [ "$VWN_LANG" = en ] && echo "Restart"                   || echo "Перезапустить")
    MSG[tor_logs]=$(          [ "$VWN_LANG" = en ] && echo "Tor logs"                  || echo "Логи Tor")
    MSG[tor_bridges]=$(       [ "$VWN_LANG" = en ] && echo "Configure Bridges"         || echo "Настройка мостов (Bridges)")
    MSG[tor_bridges_remove]=$( [ "$VWN_LANG" = en ] && echo "Remove bridges"          || echo "Удалить мосты")
    MSG[tor_remove]=$(        [ "$VWN_LANG" = en ] && echo "Remove Tor"                || echo "Удалить Tor")
    MSG[tor_bridges_status]=$( [ "$VWN_LANG" = en ] && echo "Bridges"                 || echo "Мосты")
    MSG[tor_socks5]=$(        [ "$VWN_LANG" = en ] && echo "SOCKS5"                    || echo "SOCKS5")
    MSG[tor_setup_title]=$(   [ "$VWN_LANG" = en ] && echo "=== Installing Tor ===" || echo "=== Установка Tor ===")
    MSG[tor_installing]=$(    [ "$VWN_LANG" = en ] && echo "Installing Tor..."         || echo "Установка Tor...")
    MSG[tor_installed]=$(     [ "$VWN_LANG" = en ] && echo "Tor installed."            || echo "Tor установлен.")
    MSG[tor_install_fail]=$(  [ "$VWN_LANG" = en ] && echo "Tor installation error."   || echo "Ошибка установки Tor.")
    MSG[tor_config_ok]=$(     [ "$VWN_LANG" = en ] && echo "Tor config written."       || echo "Tor конфиг записан.")
    MSG[tor_running]=$(       [ "$VWN_LANG" = en ] && echo "Tor started and working."  || echo "Tor запущен и работает.")
    MSG[tor_started]=$(       [ "$VWN_LANG" = en ] && echo "Tor started but check failed. Wait 30-60 sec." || echo "Tor запущен, но проверка не прошла. Требуется время для подключения (30-60 сек).")
    MSG[tor_installed_ok]=$(  [ "$VWN_LANG" = en ] && echo "Tor installed!"            || echo "Tor установлен!")
    MSG[tor_hint]=$(          [ "$VWN_LANG" = en ] && echo "Add domains (item 3) for Split mode." || echo "Добавьте домены в список (пункт 3) для Split режима.")
    MSG[tor_slow]=$(          [ "$VWN_LANG" = en ] && echo "Tor is slower than regular internet — Split mode recommended." || echo "Tor медленнее обычного интернета — рекомендуется Split режим.")
    MSG[tor_not_installed]=$( [ "$VWN_LANG" = en ] && echo "Install Tor first (item 1)" || echo "Сначала установите Tor (п.1)")
    MSG[tor_mode_1]=$(        [ "$VWN_LANG" = en ] && echo "1) Global — all traffic through Tor" || echo "1) Global — весь трафик через Tor")
    MSG[tor_mode_2]=$(        [ "$VWN_LANG" = en ] && echo "2) Split — only domain list" || echo "2) Split — только список доменов")
    MSG[tor_mode_3]=$(        [ "$VWN_LANG" = en ] && echo "3) OFF — disable Tor from Xray" || echo "3) OFF — отключить Tor от Xray")
    MSG[tor_global_ok]=$(     [ "$VWN_LANG" = en ] && echo "Tor Global: all traffic through Tor." || echo "Tor Global: весь трафик через Tor.")
    MSG[tor_split_ok]=$(      [ "$VWN_LANG" = en ] && echo "Tor Split applied."        || echo "Tor Split применён.")
    MSG[tor_off_ok]=$(        [ "$VWN_LANG" = en ] && echo "Tor disabled from Xray."   || echo "Tor отключён от Xray.")
    MSG[tor_domain_prompt]=$( [ "$VWN_LANG" = en ] && echo "Domain (e.g. rutracker.org): " || echo "Домен (например rutracker.org): ")
    MSG[tor_domain_added]=$(  [ "$VWN_LANG" = en ] && echo "Domain added."             || echo "Домен добавлен.")
    MSG[tor_country_select]=$( [ "$VWN_LANG" = en ] && echo "Select Tor exit country:" || echo "Выберите страну выхода Tor:")
    MSG[tor_country_auto]=$(  [ "$VWN_LANG" = en ] && echo "9) Auto (any country)"     || echo "9) Авто (любая страна)")
    MSG[tor_country_manual]=$( [ "$VWN_LANG" = en ] && echo "10) Enter code manually"  || echo "10) Ввести код вручную")
    MSG[tor_country_prompt]=$( [ "$VWN_LANG" = en ] && echo "Country code (2 letters, e.g. RO): " || echo "Код страны (2 буквы, например RO): ")
    MSG[tor_country_changed]=$( [ "$VWN_LANG" = en ] && echo "Country changed to"      || echo "Страна изменена на")
    MSG[tor_country_restarting]=$( [ "$VWN_LANG" = en ] && echo "Restarting Tor..."    || echo "Перезапуск Tor...")
    MSG[tor_remove_confirm]=$( [ "$VWN_LANG" = en ] && echo "Remove Tor?"              || echo "Удалить Tor?")
    MSG[tor_real_ip]=$(       [ "$VWN_LANG" = en ] && echo "Server real IP"            || echo "Реальный IP сервера")
    MSG[tor_ip]=$(            [ "$VWN_LANG" = en ] && echo "IP via Tor"                || echo "IP через Tor")
    MSG[tor_checking]=$(      [ "$VWN_LANG" = en ] && echo "Checking via Tor (may take 30 sec)..." || echo "Проверка через Tor (может занять 30 сек)...")
    MSG[tor_exit_country]=$(  [ "$VWN_LANG" = en ] && echo "Exit country"              || echo "Страна выхода")
    MSG[tor_circuit_sent]=$(  [ "$VWN_LANG" = en ] && echo "New circuit request sent." || echo "Запрос на новую цепь отправлен.")
    MSG[tor_circuit_title]=$( [ "$VWN_LANG" = en ] && echo "Updating Tor circuit..."   || echo "Обновление цепи Tor...")
    MSG[tor_not_running]=$(   [ "$VWN_LANG" = en ] && echo "Tor is not running."       || echo "Tor не запущен.")
    MSG[tor_bridge_title]=$(  [ "$VWN_LANG" = en ] && echo "=== Configure Tor Bridges ===" || echo "=== Настройка мостов Tor ===")
    MSG[tor_bridge_type]=$(   [ "$VWN_LANG" = en ] && echo "Bridge type:"              || echo "Тип моста:")
    MSG[tor_bridge_1]=$(      [ "$VWN_LANG" = en ] && echo "1) obfs4       — recommended, masks traffic" || echo "1) obfs4       — рекомендуется, маскирует трафик")
    MSG[tor_bridge_2]=$(      [ "$VWN_LANG" = en ] && echo "2) snowflake   — via WebRTC, hard to block" || echo "2) snowflake   — через WebRTC, сложно заблокировать")
    MSG[tor_bridge_3]=$(      [ "$VWN_LANG" = en ] && echo "3) meek-azure  — via Azure CDN" || echo "3) meek-azure  — через CDN Azure")
    MSG[tor_bridge_4]=$(      [ "$VWN_LANG" = en ] && echo "4) Enter manually (any type)" || echo "4) Ввести вручную (любой тип)")
    MSG[tor_bridge_url]=$(    [ "$VWN_LANG" = en ] && echo "Get bridges: https://bridges.torproject.org/" || echo "Получить мосты: https://bridges.torproject.org/")
    MSG[tor_bridge_choice]=$( [ "$VWN_LANG" = en ] && echo "Type [1]: "                || echo "Тип [1]: ")
    MSG[tor_bridge_paste]=$(  [ "$VWN_LANG" = en ] && echo "Paste bridge lines (one per line, empty line = end):" || echo "Вставьте строки мостов (по одной, пустая строка — конец):")
    MSG[tor_bridge_example]=$( [ "$VWN_LANG" = en ] && echo "Example: obfs4 1.2.3.4:443 FINGERPRINT cert=... iat-mode=0" || echo "Пример: obfs4 1.2.3.4:443 FINGERPRINT cert=... iat-mode=0")
    MSG[tor_bridge_empty]=$(  [ "$VWN_LANG" = en ] && echo "No bridges entered."       || echo "Мосты не введены.")
    MSG[tor_bridge_ok]=$(     [ "$VWN_LANG" = en ] && echo "Bridges configured. Tor restarted." || echo "Мосты настроены. Tor перезапущен.")
    MSG[tor_bridge_removed]=$( [ "$VWN_LANG" = en ] && echo "Bridges removed. Tor restarted." || echo "Мосты удалены. Tor перезапущен.")
    MSG[tor_obfs4_fail]=$(    [ "$VWN_LANG" = en ] && echo "Failed to install obfs4proxy/lyrebird." || echo "Не удалось установить obfs4proxy/lyrebird.")
    MSG[tor_obfs4_try]=$(     [ "$VWN_LANG" = en ] && echo "obfs4proxy not in repo, trying lyrebird..." || echo "obfs4proxy не найден в репо, пробуем lyrebird...")
}

    # ── COUNTRY LISTS ─────────────────────────────────────────────
    MSG[country_de]=$(  [ "$VWN_LANG" = en ] && echo " 1) DE — Germany"      || echo " 1) DE — Германия")
    MSG[country_nl]=$(  [ "$VWN_LANG" = en ] && echo " 2) NL — Netherlands"  || echo " 2) NL — Нидерланды")
    MSG[country_us]=$(  [ "$VWN_LANG" = en ] && echo " 3) US — USA"          || echo " 3) US — США")
    MSG[country_gb]=$(  [ "$VWN_LANG" = en ] && echo " 4) GB — UK"           || echo " 4) GB — Великобритания")
    MSG[country_fr]=$(  [ "$VWN_LANG" = en ] && echo " 5) FR — France"       || echo " 5) FR — Франция")
    MSG[country_at]=$(  [ "$VWN_LANG" = en ] && echo " 6) AT — Austria"      || echo " 6) AT — Австрия")
    MSG[country_ca]=$(  [ "$VWN_LANG" = en ] && echo " 7) CA — Canada"       || echo " 7) CA — Канада")
    MSG[country_se]=$(  [ "$VWN_LANG" = en ] && echo " 8) SE — Sweden"       || echo " 8) SE — Швеция")
    MSG[country_ch]=$(  [ "$VWN_LANG" = en ] && echo " 7) CH — Switzerland"  || echo " 7) CH — Швейцария")
    MSG[country_fi]=$(  [ "$VWN_LANG" = en ] && echo " 8) FI — Finland"      || echo " 8) FI — Финляндия")


    MSG[loading]=$(         [ "$VWN_LANG" = en ] && echo "Loading"           || echo "Загрузка")
    MSG[installed_in]=$(    [ "$VWN_LANG" = en ] && echo "installed in"      || echo "установлен в")
    MSG[run_vwn]=$(         [ "$VWN_LANG" = en ] && echo "Run: vwn"          || echo "Запустите: vwn")
    MSG[bridges_count]=$(   [ "$VWN_LANG" = en ] && echo "bridges"           || echo "мостов")
    MSG[obfs4_installing]=$( [ "$VWN_LANG" = en ] && echo "Installing obfs4proxy..." || echo "Установка obfs4proxy...")
    MSG[obfs4_already]=$(   [ "$VWN_LANG" = en ] && echo "obfs4proxy already installed." || echo "obfs4proxy уже установлен.")
    MSG[tor_already]=$(     [ "$VWN_LANG" = en ] && echo "tor already installed." || echo "tor уже установлен.")

# Функция получения строки перевода
msg() {
    echo "${MSG[$1]:-$1}"
}

# Инициализируем при загрузке модуля
_initLang
